# Authentication proxy service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-dashboard-proxy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubernetes-dashboard-proxy
    app.kubernetes.io/part-of: dashboard
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-dashboard-authenticator
  labels:
    app.kubernetes.io/name: kubernetes-dashboard-authenticator
    app.kubernetes.io/part-of: dashboard
rules:
  # List and read service accounts
  - resources:
    - serviceaccounts
    verbs:
    - get
    - list
    apiGroups:
      - ""
  # Get tokens for impersonation
  - resources:
    - secrets
    verbs:
      - get
    apiGroups:
      - ""

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-proxy
  labels:
    app.kubernetes.io/name: kubernetes-dashboard-proxy
    app.kubernetes.io/part-of: dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dashboard-authenticator
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard-proxy
    namespace: kube-system

---

apiVersion: apps/v1beta1
kind: Deployment
metadata: &deployment_metadata
  name: kubernetes-dashboard-proxy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubernetes-dashboard-proxy
    app.kubernetes.io/part-of: dashboard
spec:
  # The application is not yet designed for multiple instances
  replicas: 1
  template:
    metadata: *deployment_metadata
    spec:
      containers:
      - name: kubernetes-dashboard-proxy
        imagePullPolicy: Never # TEMP! TODO
        image: mdschweda/kubernetes-dashboard-auth
        # command:
        #   - sleep
        # args:
        #   - 9h
        env:
          - name: CONFIG_UPSTREAM
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: upstream
                optional: true
          - name: CONFIG_AUTH_PROVIDER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.provider
          - name: CONFIG_AUTH_LDAP_SERVER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.server
                optional: true
          - name: CONFIG_AUTH_LDAP_BIND_USER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.bindUser
                optional: true
          - name: CONFIG_AUTH_LDAP_BIND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-proxy-secret
                key: auth.ldap.bindPassword
                optional: true
          - name: CONFIG_AUTH_LDAP_BASE_DN
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.baseDN
                optional: true
          - name: CONFIG_AUTH_LDAP_USER_ATTRIBUTE
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.userAttribute
                optional: true
          - name: CONFIG_AUTH_GITHUB_ORGANIZATION
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.github.organization
                optional: true
          - name: CONFIG_AUTH_AZUREAD_TENANT
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.azuread.tenant
                optional: true
          - name: CONFIG_AUTH_AZUREAD_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.azuread.client.id
                optional: true
          - name: CONFIG_AUTH_AZUREAD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-proxy-secret
                key: auth.azuread.client.secret
                optional: true
        volumeMounts:
          - name: cert
            mountPath: /app/cert
          - name: acl
            mountPath: /app/acl
      serviceAccountName: kubernetes-dashboard-proxy
      automountServiceAccountToken: true
      volumes:
        - name: cert
          secret:
            secretName: kubernetes-dashboard-certs
            optional: true
            items:
              - key: dashboard.crt
                path: proxy.crt
              - key: dashboard.key
                path: proxy.key
        - name: acl
          configMap:
            name: kubernetes-dashboard-acl
            optional: true
            items:
              - key: fallback
                path: fallback
              - key: users
                path: users
              - key: groups
                path: groups
