apiVersion: apps/v1beta1
kind: Deployment
metadata: &deployment_metadata
  name: kubernetes-dashboard-proxy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubernetes-dashboard-proxy
    app.kubernetes.io/part-of: dashboard
spec:
  # The application is not yet designed for multiple instances
  replicas: 1
  template:
    metadata: *deployment_metadata
    spec:
      containers:
      - name: kubernetes-dashboard-proxy
        imagePullPolicy: Never # TEMP! TODO
        image: mdschweda/kubernetes-dashboard-auth
        # command:
        #   - sleep
        # args:
        #   - 9h
        env:
          - name: CONFIG_UPSTREAM
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: upstream
                optional: true
          - name: CONFIG_HOST_PORT_HTTP
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: host.port.http
                optional: true
          - name: CONFIG_HOST_PORT_HTTPS
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: host.port.https
                optional: true
          - name: CONFIG_AUTH_PROVIDER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.provider
          - name: CONFIG_AUTH_LDAP_SERVER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.server
                optional: true
          - name: CONFIG_AUTH_LDAP_BIND_USER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.bindUser
                optional: true
          - name: CONFIG_AUTH_LDAP_BIND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-proxy-secret
                key: auth.ldap.bindPassword
                optional: true
          - name: CONFIG_AUTH_LDAP_BASE_DN
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.baseDN
                optional: true
          - name: CONFIG_AUTH_LDAP_USER_ATTRIBUTE
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.ldap.userAttribute
                optional: true
          - name: CONFIG_AUTH_GITHUB_ORGANIZATION
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.github.organization
                optional: true
          - name: CONFIG_AUTH_AZUREAD_TENANT
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.azuread.tenant
                optional: true
          - name: CONFIG_AUTH_AZUREAD_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-proxy-config
                key: auth.azuread.client.id
                optional: true
          - name: CONFIG_AUTH_AZUREAD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-proxy-secret
                key: auth.azuread.client.secret
                optional: true
        volumeMounts:
          - name: cert
            mountPath: /app/cert
          - name: acl
            mountPath: /app/acl
      serviceAccountName: kubernetes-dashboard-proxy
      automountServiceAccountToken: true
      volumes:
        - name: cert
          secret:
            secretName: kubernetes-dashboard-certs
            items:
              - key: dashboard.crt
                path: proxy.crt
              - key: dashboard.key
                path: proxy.key
        - name: acl
          configMap:
            optional: true
            name: kubernetes-dashboard-acl
            items:
              - key: fallback
                path: fallback
              - key: users
                path: users
              - key: groups
                path: groups
