apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dashboard-auth-proxy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: dashboard-auth-proxy
    app.kubernetes.io/part-of: dashboard
spec:
  replicas: 1
  template:
    metadata:
    labels:
      app.kubernetes.io/name: dashboard-auth-proxy
      app.kubernetes.io/part-of: dashboard
    spec:
      containers:
      - name: kubernetes-dashboard-auth
        image: mdschweda/kubernetes-dashboard-auth
        # https://github.com/kubernetes/dashboard/wiki/Installation#recommended-setup
        env:
          - name: PROXY_CERT
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-certs
                key: dashboard.crt
          - name: PROXY_KEY
            valueFrom:
              secretKeyRef:
                name: kubernetes-dashboard-certs
                key: dashboard.key
          # ...
          - name: PROXY_UPSTREAM
            valueFrom:
              configMapKeyRef:
                name: kubernetes-dashboard-auth-config
                key: upstream
                optional: true
      serviceAccountName: kubernetes-dashboard
